title: "lyn0310 Blog"
name: "lyn0310"
description: "개발 기록 블로그"
url: "https://lyn0310.github.io"
baseurl: ""

# 테마 설정 (핵심)
remote_theme: "mmistakes/minimal-mistakes"

# 필수 플러그인
plugins:
  - jekyll-include-cache
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# paginate: 5
# paginate_path: "/page:num/"

# 네비게이션 메뉴
nav:
  - title: "Home"
    url: /
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/
  - title: "About"
    url: /about/
# 포스트 설정
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# 미래 날짜 허용
future: true

# Author 설정
author:
  name: "Yuna Lee (lyn0310)"
  avatar: "/assets/images/profile.jpg"
  bio: "개발자 | 블로그에 개발 기록을 남깁니다."
  location: "Seoul, South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lyn0310"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rosaleeyuna43@gmail.com"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/luy._.una"


# 포스트에 기본 설정 적용
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true