title: "lyn0310 Blog"
name: "lyn0310"
description: "개발 기록 블로그"
url: "https://lyn0310.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

future: true

plugins:
  - jekyll-include-cache
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# paginate: 5
# paginate_path: "/page:num/"

sass:
  sass_dir: _sass
  style: compressed

author:
  name: "Yuna Lee (lyn0310)"
  avatar: "/assets/images/profile.jpg"
  bio: "개발 기록 블로그"
  location: "Seoul, South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lyn0310"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rosaleeyuna43@gmail.com"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/luy._.una"

nav:
  - title: "Home"
    url: /
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/
  - title: "About"
    url: /about/
    
collections:
  posts:
    output: true
    permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_label: "Contents"
      toc_icon: "list"